### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by Pennybebraver** [parklab/xTea#7] opened 2021-07-07 02:37 UTC
Hi Simon,

I followed up my question here in case the closed issue won't send you a notification. Sorry if I send the twice.

I downloaded the latest version xTea 1.1 recently but got a similar error message as Jainy's (issue #5) as below:

Traceback (most recent call last):
File "/n/data1/bch/genetics/lee/penny/xTea_1_1/xtea/x_TEA_main.py", line 1031, in
pkl_model = gc.load_model_from_file(sf_model)
File "/n/data1/bch/genetics/lee/penny/xTea_1_1/xtea/x_genotype_classify.py", line 182, in load_model_from_file
pickle_model = pickle.load(file, encoding='latin1')
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'
sort: cannot read: /n/data1/bch/genetics/lee/penny/xTea_1000_genome/working_dir/HG00740/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Running command: sort -k1,1V -k2,2n -o /n/data1/bch/genetics/lee/penny/xTea_1000_genome/working_dir/HG00740/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /n/data1/bch/genetics/lee/penny/xTea_1000_genome/working_dir/HG00740/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

Traceback (most recent call last):
File "/n/data1/bch/genetics/lee/penny/xTea_1_1/xtea/x_TEA_main.py", line 1065, in
gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
File "/n/data1/bch/genetics/lee/penny/xTea_1_1/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/n/data1/bch/genetics/lee/penny/xTea_1000_genome/working_dir/HG00740/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted'

I am not sure whether the following errors are causing by "ModuleNotFoundError: No module named 'sklearn.ensemble.forest'". Also, the scikit-learn version that I installed is 0.21.3 and I am using Python 3.7.4. Would you help take a look at that?

Thank you so much!

Best,
Penny

**Comment by simoncchu** [comment] 2021-07-23 21:22
@Pennybebraver  Penny, I noticed this issue. And I think this is caused by incompatible between sklearn version and python version. I am going to train a new model with the latest version and release soon, which can fully solve this problem. I will keep this issue open for now.

**Comment by dr-ashu-geno** [comment] 2021-12-20 02:53
Dear @simoncchu 

I have the same issue although I'm using python3.9 and my scikit-learn version is 0.24.2 (so I expect these are compatible). 

Traceback (most recent call last):
  File "/home/data/xTea/xTea/xtea/x_TEA_main.py", line 1031, in <module>
    pkl_model = gc.load_model_from_file(sf_model)
  File "home/data/xTea/xTea/xtea/x_genotype_classify.py", line 182, in load_model_from_file
    pickle_model = pickle.load(file, encoding='latin1')
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

Any help for this case please?

Thank you in advance,
Best,

**Comment by simoncchu** [comment] 2021-12-20 02:56
@dr-ashu-geno is possible for you to try with python 3.7? I am sorry for the inconvenience. I'll release a version fully skip these libs in the next release.

**Comment by dr-ashu-geno** [comment] 2021-12-20 06:03
@simoncchu Thank you so much for your quick reply. 
I installed python3.7 and scikit-learn 0.21.3 and it worked. 

Best regards,

**Comment by rglenning-imp** [comment] 2021-12-28 19:45
> @simoncchu Thank you so much for your quick reply. I installed python3.7 and scikit-learn 0.21.3 and it worked.
> 
> Best regards,

This also fixed my issue

**Comment by simoncchu** [comment] 2022-04-20 19:45
A new genotyping calling module is updated (see readme bottom), which does not require the sklean.ensemble.forest module anymore. For now, only for non-conda version. Please have a try. I'll close this ticket for now.

**Closed by simoncchu** 2022-04-20 19:45 UTC
Labels: enhancement
